export const SAGA_DOCUMENT_CATEGORY_LIST = 'SAGA_DOCUMENT_CATEGORY_LIST'
export const SAGA_CREATE_DOCUMENT_CATEGORY = 'SAGA_CREATE_DOCUMENT_CATEGORY'
export const SAGA_EDIT_DOCUMENT_CATEGORY = 'SAGA_EDIT_DOCUMENT_CATEGORY'
export const SAGA_DELETE_DOCUMENT_CATEGORY = 'SAGA_DELETE_DOCUMENT_CATEGORY'

export const FETCH_DOCUMENT_CATEGORY_LIST = 'FETCH_DOCUMENT_CATEGORY_LIST'
export const FETCH_CURRENT_DOCUMENT_CATEGORY = 'FETCH_CURRENT_DOCUMENT_CATEGORY'

export const SHOW_CREATE_DOCUMENT_CATEGORY_MODAL = 'SHOW_CREATE_DOCUMENT_CATEGORY_MODAL'
export const HIDE_CREATE_DOCUMENT_CATEGORY_MODAL = 'HIDE_CREATE_DOCUMENT_CATEGORY_MODAL'

export const SHOW_EDIT_DOCUMENT_CATEGORY_MODAL = 'SHOW_EDIT_DOCUMENT_CATEGORY_MODAL'
export const HIDE_EDIT_DOCUMENT_CATEGORY_MODAL = 'HIDE_EDIT_DOCUMENT_CATEGORY_MODAL'
